//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FTWldap.rc
//
#define IDS_LOGMSG_LOOKINGFORDOMAINCONTROLLER 20001
#define IDS_LOGMSG_FOUNDDOMAINCONTROLLER 20002
#define IDS_LOGMSG_USINGDOMAINCONTROLLER 20003

#define IDS_LOGERROR_DIDNOTFINDDOMAINCONTROLLER 21001
#define IDS_LOGERROR_CANNOTUSEDDOMAINCONTROLLER 21002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
