//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UI++REST.rc
//

#define IDS_LOGMSG_SETTSVARIABLE		11012
#define IDS_LOGERROR_SETTSVARIABLE		12002

#define IDS_LOGMSG_ACTIONREGISTERED		20001
#define IDS_LOGMSG_NOVALIDURL			21001
#define IDS_LOGMSG_RESTCALL				21002
#define IDS_LOGMSG_RESTSUCCESS			21003
#define IDS_LOGMSG_FOUNDJSONVALUE		21004
#define IDS_LOGMSG_FOUNDNONSTRINGJSONVALUE	21005

#define IDS_LOGERROR_RESTFAIL			22001
#define IDS_LOGERROR_JSONPARSE			22002
#define IDS_LOGERROR_RESTNOPARAMS		22003

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE	1000
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		1000
#define _APS_NEXT_COMMAND_VALUE		32771
#endif
#endif
